# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao4',
            name='density',
            field=models.FloatField(null=True),
        ),
    ]
